// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryTrackWeb.Models
{
    public partial class GetAll_ProductResult
    {
        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public int? Stock { get; set; }
        public string Description { get; set; }
        public decimal UnitCost { get; set; }
        public decimal UnitCostSale { get; set; }
        public decimal? Total { get; set; }
        public DateTime? Date { get; set; }
    }
}
