// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryTrackWeb.Models
{
    public partial class Remuneration
    {
        public string RemuId { get; set; }
        public int? SalerId { get; set; }
        public decimal Amount { get; set; }
        public int Done { get; set; }

        public virtual Saler Saler { get; set; }
    }
}