// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace InventoryTrackWeb.Models
{
    public partial class Saler
    {
        public Saler()
        {
            Remunerations = new HashSet<Remuneration>();
        }

        public int SalerId { get; set; }
        public byte[] SalerName { get; set; }
        public string TelefoneNumber { get; set; }

        public virtual ICollection<Remuneration> Remunerations { get; set; }
    }
}