// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using InventoryTrackWeb.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace InventoryTrackWeb.Models.Context
{
    public partial interface IInventoryTrackTestContextProcedures
    {
        Task<List<GetAll_ProductResult>> GetAll_ProductAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
